spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/team?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: local_db_pw

google:
    url: https://oauth2.googleapis.com/token
    clientId: 337016807216-87ttk4eopkm6to64i8cdk9br54hmlpob.apps.googleusercontent.com
    clientSecret: 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
    scope: email+profile
