spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/team?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: local_db_pw