version: "3.7"

services:
  app:
    image: mysql:8.0.29
    container_name: team-bo-local-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=team
      - MYSQL_ROOT_PASSWORD=local_db_pw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci